// <auto-generated />
using System;
using InfinityBox.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InfinityBox.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("EffectPassive", b =>
                {
                    b.Property<int>("EffectsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PassivesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EffectsId", "PassivesId");

                    b.HasIndex("PassivesId");

                    b.ToTable("EffectPassive");
                });

            modelBuilder.Entity("EffectSkill", b =>
                {
                    b.Property<int>("EffectsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SkillsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EffectsId", "SkillsId");

                    b.HasIndex("SkillsId");

                    b.ToTable("EffectSkill");
                });

            modelBuilder.Entity("EffectStatModifier", b =>
                {
                    b.Property<int>("EffectsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatModifiersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EffectsId", "StatModifiersId");

                    b.HasIndex("StatModifiersId");

                    b.ToTable("EffectStatModifier");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseExperience")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.CharacterStat", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("CharacterId", "StatId");

                    b.HasIndex("StatId");

                    b.ToTable("CharacterStats");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.CharacterType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CharacterTypes");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Effect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Effects");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Evolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("LevelRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("CharacterTypeId");

                    b.ToTable("Evolutions");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EvolutionId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("InventoryId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvolutionId");

                    b.HasIndex("InventoryId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Passive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Passives");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cooldown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Stat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("UserCharacterId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserCharacterId");

                    b.ToTable("Stats");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.StatModifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculateType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTarget")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Rate")
                        .HasColumnType("REAL");

                    b.Property<int>("StatType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StatModifiers");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.UserBank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserBanks");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.UserCharacter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EvolutionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Stars")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EvolutionId");

                    b.ToTable("UserCharacters");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.UserPocket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserPockets");
                });

            modelBuilder.Entity("EffectPassive", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Effect", null)
                        .WithMany()
                        .HasForeignKey("EffectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfinityBox.Domain.Entities.Passive", null)
                        .WithMany()
                        .HasForeignKey("PassivesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EffectSkill", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Effect", null)
                        .WithMany()
                        .HasForeignKey("EffectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfinityBox.Domain.Entities.Skill", null)
                        .WithMany()
                        .HasForeignKey("SkillsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EffectStatModifier", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Effect", null)
                        .WithMany()
                        .HasForeignKey("EffectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfinityBox.Domain.Entities.StatModifier", null)
                        .WithMany()
                        .HasForeignKey("StatModifiersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Character", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.CharacterType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.CharacterStat", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Character", "Character")
                        .WithMany("CharacterStats")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfinityBox.Domain.Entities.Stat", "Stat")
                        .WithMany("CharacterStats")
                        .HasForeignKey("StatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Evolution", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Character", null)
                        .WithMany("Evolutions")
                        .HasForeignKey("CharacterId");

                    b.HasOne("InfinityBox.Domain.Entities.CharacterType", "CharacterType")
                        .WithMany()
                        .HasForeignKey("CharacterTypeId");

                    b.Navigation("CharacterType");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Item", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Evolution", null)
                        .WithMany("Materials")
                        .HasForeignKey("EvolutionId");

                    b.HasOne("InfinityBox.Domain.Entities.Inventory", null)
                        .WithMany("Items")
                        .HasForeignKey("InventoryId");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Passive", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Character", null)
                        .WithMany("Passives")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Skill", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Character", null)
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Stat", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.UserCharacter", null)
                        .WithMany("Stats")
                        .HasForeignKey("UserCharacterId");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.UserCharacter", b =>
                {
                    b.HasOne("InfinityBox.Domain.Entities.Character", "Character")
                        .WithMany("UserCharacters")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InfinityBox.Domain.Entities.Evolution", "Evolution")
                        .WithMany()
                        .HasForeignKey("EvolutionId");

                    b.Navigation("Character");

                    b.Navigation("Evolution");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Character", b =>
                {
                    b.Navigation("CharacterStats");

                    b.Navigation("Evolutions");

                    b.Navigation("Passives");

                    b.Navigation("Skills");

                    b.Navigation("UserCharacters");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Evolution", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.Stat", b =>
                {
                    b.Navigation("CharacterStats");
                });

            modelBuilder.Entity("InfinityBox.Domain.Entities.UserCharacter", b =>
                {
                    b.Navigation("Stats");
                });
#pragma warning restore 612, 618
        }
    }
}
